<?php
$readingQuestions = [];

$passages = [
    [
        "text" => "Bioluminescence is the biochemical emission of light by living organisms such as fireflies, deep-sea fishes, and certain fungi. In the dark depths of the ocean, where sunlight cannot penetrate, bioluminescence serves several vital functions. For some species, it acts as a camouflage mechanism known as counterillumination. By emitting light from their undersides that matches the faint light coming from the surface, these creatures become virtually invisible to predators lurking below. Other species use bioluminescence as a lure; the anglerfish, for example, dangles a glowing appendage in front of its mouth to attract unsuspecting prey. Furthermore, bioluminescence can be used as a defense mechanism to startle predators or to attract a predator's predator. The chemical reaction that produces this light involves a light-emitting molecule called luciferin and an enzyme called luciferase. This fascinating adaptation highlights the incredible evolutionary strategies organisms have developed to survive in some of the Earth's most extreme and inhospitable environments.",
        "questions" => [
            ["q" => "What is the main topic of the passage?", "a" => "The discovery of luciferin", "b" => "The survival functions of bioluminescence in deep-sea creatures", "c" => "How fireflies produce light", "d" => "The evolution of the anglerfish", "ans" => "b", "exp" => "The passage focuses on what bioluminescence is and how it helps organisms survive in the deep ocean."],
            ["q" => "The word 'vital' in the passage is closest in meaning to...", "a" => "optional", "b" => "essential", "c" => "vibrant", "d" => "deadly", "ans" => "b", "exp" => "'Vital' means absolutely necessary or essential."],
            ["q" => "How does counterillumination help deep-sea creatures?", "a" => "It blinds their prey.", "b" => "It makes them invisible to predators below them.", "c" => "It helps them see in the dark.", "d" => "It attracts mates.", "ans" => "b", "exp" => "The passage states: 'By emitting light... these creatures become virtually invisible to predators lurking below.'"],
            ["q" => "According to the passage, how does the anglerfish use bioluminescence?", "a" => "To startle predators", "b" => "To camouflage itself", "c" => "To attract prey", "d" => "To illuminate its path", "ans" => "c", "exp" => "The anglerfish 'dangles a glowing appendage... to attract unsuspecting prey.'"],
            ["q" => "The word 'lure' in the passage is closest in meaning to...", "a" => "trap", "b" => "bait", "c" => "warning", "d" => "weapon", "ans" => "b", "exp" => "A 'lure' is something used to attract or bait an animal."],
            ["q" => "What two components are necessary for the chemical reaction that produces bioluminescence?", "a" => "Sunlight and water", "b" => "Fireflies and fungi", "c" => "Luciferin and luciferase", "d" => "Oxygen and carbon dioxide", "ans" => "c", "exp" => "The reaction involves 'a light-emitting molecule called luciferin and an enzyme called luciferase.'"],
            ["q" => "The word 'inhospitable' in the passage is closest in meaning to...", "a" => "welcoming", "b" => "unfriendly and harsh", "c" => "crowded", "d" => "warm", "ans" => "b", "exp" => "'Inhospitable' refers to environments that are harsh and difficult to survive in."],
            ["q" => "Which of the following is NOT mentioned as a function of bioluminescence?", "a" => "Camouflage", "b" => "Attracting prey", "c" => "Regulating body temperature", "d" => "Startling predators", "ans" => "c", "exp" => "Regulating body temperature is not mentioned in the passage."],
            ["q" => "The word 'their' in the passage refers to...", "a" => "predators", "b" => "anglerfish", "c" => "these creatures", "d" => "fungi", "ans" => "c", "exp" => "'...light from their undersides...' refers back to 'these creatures'."],
            ["q" => "What can be inferred about the depths of the ocean from the passage?", "a" => "It is heavily populated by plants.", "b" => "It receives no sunlight.", "c" => "It is too cold for most fish.", "d" => "It is a very safe environment.", "ans" => "b", "exp" => "The passage explicitly states 'where sunlight cannot penetrate'."]
        ]
    ],
    [
        "text" => "Neuroplasticity, or brain plasticity, refers to the brain's remarkable ability to reorganize itself by forming new neural connections throughout life. For a long time, it was believed that the adult brain was a static organ, meaning that once its physical structure was fully formed during childhood, it could not be altered. However, modern neuroscience has proven this to be a misconception. Neuroplasticity allows the neurons in the brain to compensate for injury and disease and to adjust their activities in response to new situations or to changes in their environment. When we learn a new skill, such as playing a musical instrument or speaking a new language, the brain physically changes; certain areas become denser with neural pathways. Conversely, pathways that are rarely used may weaken and eventually be pruned away, a process known as synaptic pruning. This adaptability provides hope for stroke survivors and individuals with brain injuries, as rehabilitation can help the brain rewire around damaged areas.",
        "questions" => [
            ["q" => "What is the main idea of the passage?", "a" => "The brain cannot heal after a stroke.", "b" => "Neuroplasticity is the brain's ability to reorganize and adapt throughout life.", "c" => "Learning a new language is the only way to change the brain.", "d" => "The adult brain is a static and unchangeable organ.", "ans" => "b", "exp" => "The passage explains neuroplasticity and how the brain adapts and changes throughout life."],
            ["q" => "What was the traditional belief about the adult brain?", "a" => "It grew continuously.", "b" => "It was a static organ that could not be altered.", "c" => "It could easily recover from injuries.", "d" => "It possessed high neuroplasticity.", "ans" => "b", "exp" => "The text says: 'it was believed that the adult brain was a static organ... it could not be altered.'"],
            ["q" => "The word 'misconception' in the passage is closest in meaning to...", "a" => "scientific fact", "b" => "false belief", "c" => "new discovery", "d" => "proven theory", "ans" => "b", "exp" => "A 'misconception' is a view or opinion that is incorrect or based on a false belief."],
            ["q" => "According to the passage, what happens physically to the brain when a new skill is learned?", "a" => "It grows larger in size.", "b" => "It sheds old memories.", "c" => "Certain areas become denser with neural pathways.", "d" => "It becomes static.", "ans" => "c", "exp" => "The passage states: 'certain areas become denser with neural pathways.'"],
            ["q" => "What is 'synaptic pruning' as described in the passage?", "a" => "The rapid creation of new brain cells", "b" => "The weakening and removal of rarely used neural pathways", "c" => "The surgical removal of damaged brain tissue", "d" => "The process of learning a musical instrument", "ans" => "b", "exp" => "'...pathways that are rarely used may weaken and eventually be pruned away, a process known as synaptic pruning.'"],
            ["q" => "The word 'compensate' in the passage is closest in meaning to...", "a" => "make up for", "b" => "worsen", "c" => "ignore", "d" => "complicate", "ans" => "a", "exp" => "To 'compensate' means to make up for a weakness or injury."],
            ["q" => "Why does neuroplasticity provide hope for stroke survivors?", "a" => "Because it cures the underlying cause of strokes.", "b" => "Because it guarantees they will not have another stroke.", "c" => "Because rehabilitation can help the brain rewire around damaged areas.", "d" => "Because it replaces lost brain cells with artificial ones.", "ans" => "c", "exp" => "The text explicitly notes: 'rehabilitation can help the brain rewire around damaged areas.'"],
            ["q" => "The word 'adaptability' in the passage refers to...", "a" => "The static nature of the brain", "b" => "The process of synaptic pruning", "c" => "The brain's ability to change and reorganize", "d" => "The loss of neural pathways", "ans" => "c", "exp" => "'Adaptability' refers to the brain's neuroplasticity mentioned throughout."],
            ["q" => "Which of the following is an example of neuroplasticity given in the text?", "a" => "Losing a musical instrument", "b" => "Learning a new language", "c" => "Sleeping for 8 hours", "d" => "Eating a healthy diet", "ans" => "b", "exp" => "'When we learn a new skill, such as playing a musical instrument or speaking a new language...'"],
            ["q" => "It can be inferred from the passage that...", "a" => "Children have no neuroplasticity.", "b" => "Neuroplasticity only occurs during childhood.", "c" => "The brain's structure is constantly changing based on experiences.", "d" => "Synaptic pruning only happens to stroke victims.", "ans" => "c", "exp" => "Because the brain changes when learning and prunes unused pathways, its structure is constantly changing based on experience."]
        ]
    ],
    [
        "text" => "The Silk Road was an ancient network of trade routes that connected the East and West, facilitating cultural, economic, and political interactions between regions from the second century BCE to the 18th century. It was not a single, paved road, but rather a complex web of land and sea routes stretching from China to the Mediterranean. The route derives its name from the lucrative trade in Chinese silk, which was highly sought after in Rome and other Western empires. However, silk was far from the only commodity exchanged. Spices, precious metals, glassware, and paper also traveled along these paths. Perhaps more importantly, the Silk Road served as a conduit for the transmission of ideas, religions, and technologies. Buddhism spread from India to China, and Chinese inventions like the compass and gunpowder eventually made their way to Europe. Unfortunately, the trade network also facilitated the spread of diseases, most notably the bubonic plague, which devastated populations in Asia and Europe during the Middle Ages.",
        "questions" => [
            ["q" => "What is the main idea of the passage?", "a" => "The Silk Road was solely used for trading silk.", "b" => "The Silk Road was a paved highway across Asia.", "c" => "The Silk Road was a crucial network for the exchange of goods, culture, and ideas.", "d" => "The Silk Road was the primary cause of the bubonic plague.", "ans" => "c", "exp" => "The passage discusses the Silk Road as a network that facilitated cultural, economic, and political interactions."],
            ["q" => "Why was the network of routes named the 'Silk Road'?", "a" => "Because the roads were lined with silk", "b" => "Because it was the only route to find silk worms", "c" => "Because of the lucrative trade in Chinese silk", "d" => "Because Chinese emperors demanded it", "ans" => "c", "exp" => "The passage states: 'The route derives its name from the lucrative trade in Chinese silk...'"],
            ["q" => "The word 'lucrative' in the passage is closest in meaning to...", "a" => "dangerous", "b" => "profitable", "c" => "ancient", "d" => "complicated", "ans" => "b", "exp" => "'Lucrative' means producing a great deal of profit."],
            ["q" => "According to the passage, the Silk Road was...", "a" => "A single, unbroken paved road", "b" => "A complex web of land and sea routes", "c" => "A route used exclusively by the military", "d" => "A short path between India and China", "ans" => "b", "exp" => "The text explicitly says: 'It was not a single, paved road, but rather a complex web of land and sea routes...'"],
            ["q" => "Which of the following was NOT traded on the Silk Road according to the passage?", "a" => "Spices", "b" => "Gunpowder", "c" => "Glassware", "d" => "Coffee", "ans" => "d", "exp" => "Spices, gunpowder, and glassware are mentioned. Coffee is not."],
            ["q" => "The word 'conduit' in the passage is closest in meaning to...", "a" => "barrier", "b" => "channel", "c" => "obstacle", "d" => "destination", "ans" => "b", "exp" => "A 'conduit' is a channel for conveying water or other fluid, or in this context, a channel for transmission."],
            ["q" => "What significant cultural exchange is mentioned in the passage?", "a" => "The spread of Christianity to China", "b" => "The spread of Buddhism from India to China", "c" => "The introduction of Roman law to Asia", "d" => "The transmission of Greek philosophy", "ans" => "b", "exp" => "The text states: 'Buddhism spread from India to China...'"],
            ["q" => "The word 'devastated' in the passage is closest in meaning to...", "a" => "improved", "b" => "destroyed or severely damaged", "c" => "bypassed", "d" => "populated", "ans" => "b", "exp" => "'Devastate' means to destroy or ruin something."],
            ["q" => "What negative impact of the Silk Road is discussed?", "a" => "It caused wars between East and West.", "b" => "It led to the bankruptcy of the Roman Empire.", "c" => "It facilitated the spread of diseases like the bubonic plague.", "d" => "It destroyed local cultures.", "ans" => "c", "exp" => "The passage notes: 'the trade network also facilitated the spread of diseases, most notably the bubonic plague...'"],
            ["q" => "It can be inferred from the passage that...", "a" => "The Silk Road only existed for a few decades.", "b" => "Trade on the Silk Road had global consequences.", "c" => "Only merchants from China traveled the Silk Road.", "d" => "The Silk Road was entirely peaceful.", "ans" => "b", "exp" => "Because goods, diseases, and technologies spread across continents, the consequences were global."]
        ]
    ],
    [
        "text" => "The solar system formed approximately 4.6 billion years ago from a giant cloud of gas and dust known as the solar nebula. According to the nebular hypothesis, this cloud began to collapse under its own gravity, possibly triggered by the shockwave of a nearby supernova. As the nebula collapsed, it began to spin faster and flatten into a disk. Most of the material was pulled toward the center to form the Sun. The remaining gas and dust in the spinning disk began to clump together due to gravity, forming small bodies called planetesimals. Over millions of years, these planetesimals collided and merged to form the planets, moons, and asteroids we see today. The inner planets, including Earth, are terrestrial, composed primarily of rock and metal, because the intense heat of the early Sun vaporized lighter materials like water and gas in the inner solar system. Conversely, the outer planets, such as Jupiter and Saturn, formed farther from the Sun where temperatures were cool enough for ice and gases to condense, resulting in massive gas giants.",
        "questions" => [
            ["q" => "What is the primary focus of the passage?", "a" => "The differences between Jupiter and Saturn", "b" => "The formation of the solar system according to the nebular hypothesis", "c" => "The life cycle of a supernova", "d" => "The composition of the Earth", "ans" => "b", "exp" => "The passage explains how the solar system, including the sun and planets, formed from a solar nebula."],
            ["q" => "According to the passage, what triggered the collapse of the solar nebula?", "a" => "A collision between two stars", "b" => "The gravity of a black hole", "c" => "Possibly the shockwave of a nearby supernova", "d" => "The intense heat of the Sun", "ans" => "c", "exp" => "The text says it collapsed under its own gravity, 'possibly triggered by the shockwave of a nearby supernova.'"],
            ["q" => "The word 'collapse' in the passage is closest in meaning to...", "a" => "expand", "b" => "explode", "c" => "fall inward", "d" => "stabilize", "ans" => "c", "exp" => "To collapse under gravity means to fall inward or contract."],
            ["q" => "What happened to most of the material in the collapsing nebula?", "a" => "It formed the outer planets.", "b" => "It was blown away by the supernova.", "c" => "It was pulled toward the center to form the Sun.", "d" => "It turned into asteroids.", "ans" => "c", "exp" => "The passage explicitly states: 'Most of the material was pulled toward the center to form the Sun.'"],
            ["q" => "What are 'planetesimals'?", "a" => "Giant clouds of gas", "b" => "Small bodies formed from clumping gas and dust", "c" => "The moons of Jupiter", "d" => "Exploding stars", "ans" => "b", "exp" => "They are described as 'small bodies' formed when gas and dust in the disk began to clump together."],
            ["q" => "Why are the inner planets composed primarily of rock and metal?", "a" => "Because they formed from a different nebula", "b" => "Because the intense heat of the early Sun vaporized lighter materials", "c" => "Because they absorbed all the gas from the outer planets", "d" => "Because they are older than the outer planets", "ans" => "b", "exp" => "The text states: 'because the intense heat of the early Sun vaporized lighter materials like water and gas in the inner solar system.'"],
            ["q" => "The word 'condense' in the passage is closest in meaning to...", "a" => "evaporate", "b" => "expand", "c" => "turn from gas into liquid or solid", "d" => "ignite", "ans" => "c", "exp" => "'Condense' means to change from a gas to a denser state, like liquid or solid."],
            ["q" => "According to the passage, which planets are considered gas giants?", "a" => "Earth and Mars", "b" => "Venus and Mercury", "c" => "Jupiter and Saturn", "d" => "All outer planets", "ans" => "c", "exp" => "The passage mentions 'outer planets, such as Jupiter and Saturn... resulting in massive gas giants.'"],
            ["q" => "The word 'these' in the passage refers to...", "a" => "planets", "b" => "planetesimals", "c" => "gases", "d" => "moons", "ans" => "b", "exp" => "'...these planetesimals collided and merged...' refers to the previously mentioned planetesimals."],
            ["q" => "It can be inferred from the passage that the outer solar system was...", "a" => "hotter than the inner solar system.", "b" => "cooler than the inner solar system.", "c" => "devoid of gravity.", "d" => "mostly made of rock and metal.", "ans" => "b", "exp" => "The passage states that the outer planets formed 'where temperatures were cool enough for ice and gases to condense'."]
        ]
    ],
    [
        "text" => "The aqueducts of ancient Rome stand as a testament to the advanced engineering capabilities of the Roman Empire. Designed to supply fresh water to the city's baths, fountains, and private households, these monumental structures revolutionized urban living. While the most visible parts of the aqueducts are the grand stone arches stretching across valleys, the majority of the system actually ran underground. This subterranean design protected the water from contamination and enemies, and minimized structural damage from weather. Roman engineers relied entirely on gravity to move the water, meaning the aqueducts had to be constructed with a slight, continuous downward gradient over distances that sometimes exceeded 50 miles. To maintain this precise slope across uneven terrain, they utilized specialized surveying tools like the chorobates. Upon reaching the city, the water flowed into a castellum aquae, a main distribution tank, before being channeled through lead or clay pipes to various destinations. The success of this system allowed Rome to sustain a population of over a million people, an unprecedented feat in antiquity.",
        "questions" => [
            ["q" => "What is the main purpose of the passage?", "a" => "To criticize Roman architecture", "b" => "To explain how Roman aqueducts worked and their significance", "c" => "To describe the invention of the chorobates", "d" => "To discuss the daily life of ancient Romans", "ans" => "b", "exp" => "The passage details the engineering of the aqueducts and their impact on Rome."],
            ["q" => "According to the passage, where was the majority of the aqueduct system located?", "a" => "Above ground on stone arches", "b" => "Inside private households", "c" => "Underground", "d" => "On mountain peaks", "ans" => "c", "exp" => "The text states: 'the majority of the system actually ran underground.'"],
            ["q" => "Why did Roman engineers build much of the aqueduct system underground?", "a" => "To hide their wealth from the citizens", "b" => "To protect the water from contamination and enemies", "c" => "Because they lacked the stone to build arches", "d" => "Because gravity works better underground", "ans" => "b", "exp" => "The subterranean design 'protected the water from contamination and enemies, and minimized structural damage.'"],
            ["q" => "The word 'gradient' in the passage is closest in meaning to...", "a" => "slope", "b" => "speed", "c" => "tunnel", "d" => "bridge", "ans" => "a", "exp" => "A 'gradient' refers to an inclined part of a road or railway; a slope."],
            ["q" => "How was water moved through the aqueducts?", "a" => "By mechanical pumps", "b" => "By relying entirely on gravity", "c" => "By using water wheels", "d" => "By animal labor", "ans" => "b", "exp" => "The passage says: 'Roman engineers relied entirely on gravity to move the water...'"],
            ["q" => "What was the function of the chorobates?", "a" => "To filter the water", "b" => "To distribute water to private homes", "c" => "To maintain a precise downward slope across uneven terrain", "d" => "To act as a main distribution tank", "ans" => "c", "exp" => "It was a surveying tool utilized 'To maintain this precise slope across uneven terrain.'"],
            ["q" => "The word 'unprecedented' in the passage is closest in meaning to...", "a" => "common", "b" => "never done or known before", "c" => "unsuccessful", "d" => "dangerous", "ans" => "b", "exp" => "'Unprecedented' means without previous instance; never before known or experienced."],
            ["q" => "What happened to the water when it reached the city?", "a" => "It flowed into a castellum aquae", "b" => "It was boiled to ensure purity", "c" => "It was sold to the highest bidder", "d" => "It flooded the streets", "ans" => "a", "exp" => "The text states: 'Upon reaching the city, the water flowed into a castellum aquae, a main distribution tank...'"],
            ["q" => "What material were the distribution pipes made of?", "a" => "Wood or iron", "b" => "Lead or clay", "c" => "Stone or marble", "d" => "Bronze or copper", "ans" => "b", "exp" => "The water was 'channeled through lead or clay pipes'."],
            ["q" => "What was the ultimate impact of the aqueduct system on Rome?", "a" => "It caused widespread disease.", "b" => "It led to the invention of modern plumbing.", "c" => "It allowed the city to sustain a population of over a million people.", "d" => "It drained all the surrounding lakes.", "ans" => "c", "exp" => "The passage concludes: 'The success of this system allowed Rome to sustain a population of over a million people...'"]
        ]
    ]
];

foreach ($passages as $passage) {
    foreach ($passage['questions'] as $q) {
        $readingQuestions[] = [
            "question_text" => $q['q'],
            "passage_text" => $passage['text'],
            "option_a" => $q['a'],
            "option_b" => $q['b'],
            "option_c" => $q['c'],
            "option_d" => $q['d'],
            "correct_answer" => strtoupper($q['ans']),
            "explanation" => $q['exp'],
            "difficulty" => "medium"
        ];
    }
}

file_put_contents(__DIR__ . '/reading_questions.json', json_encode($readingQuestions, JSON_PRETTY_PRINT));
echo "Successfully generated 50 NEW Reading Questions in reading_questions.json\n";
